### ISSUE TITLE
CAPITAL_IDENT werkt niet voor ParWidth

### ISSUE THREAD

**Issue by JowJoris** [michelportier/icss#6]
Bij level1.icss wordt gevraagd om ParWidth aan width te koppelen. Het regex pattern voor CAPITAL_IDENT `[A-Z] [A-Za-z0-9_]*` werkt niet bij ParWidth. Ik denk dat dit verandert moet worden in `[A-Z]+[A-Za-z0-9_]*`

**Comment by sanmai-NL** [comment]
Waarom werkt het niet? Leg maar uit waar de match misgaat. Waarom denk je dat dit veranderd moet worden in jouw voorstel?

**Comment by JowJoris** [comment]
Omdat een spatie niet kan worden gevonden binnen `ParWidth`  die er nu volgens `[A-Z] [A-Za-z0-9_]*` wel hoort te zijn. Waarschijnlijk lost Antlr4 dit intern op maar het hoort niet. Een verbetering voor het pattern is `[A-Z][A-Za-z0-9_]*` in plaats van mijn hiervoor gesuggereerde oplossing.

**Comment by AhmetFUsta** [comment]
De spatie is in dit geval een separator voor de Regular Expressions, dus het zijn eigenlijk twee aparte Regular Expressions.

**Comment by sanmai-NL** [comment]
@JowJoris, komt de syntaxis van [`java.lang.String.matches`](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/String.html#matches(java.lang.String)) dan overeen met de [lexer](https://github.com/antlr/grammars-v4/blob/7bf8a8de15a23c176763c2f8c5eba30305d22946/antlr4/ANTLRv4Lexer.g4) en [parser](https://github.com/antlr/grammars-v4/blob/7bf8a8de15a23c176763c2f8c5eba30305d22946/antlr4/ANTLRv4Parser.g4)-regels voor ANTLR 4 grammatica's? Je ziet ook in de rest van de ICSS-grammatica dat de pragmatiek is: onderdelen van regels scheiden met een spatie. Waarom zou je daar dan van willen afwijken in dit ene geval?

**Comment by JowJoris** [comment]
@sanmai-NL Nee de syntaxis komt uiteraard niet overeen, het viel mij alleen op dat er een spatie tussenin stond in de regex en dat ik het met spatie niet werkend kreeg bij het gebruiken in combinatie met `java.lang.String.matches()` en ik er daarom van uit ging dat er een typfout was gemaakt.  Niet bij nagedacht dat de regex regels van Java en ANTLR4 verschillend zijn zoals hieruit blijkt.
